### ISSUE TITLE
[MELHORIA] Cadastro de UF

### ISSUE THREAD

**Issue by dougs007** [orionteles/iesb-eleicoes#8]
- [ ] Criar tela para alimentar a tabela de UF.

Obs: Digamos que amanhã teremos um UF novo, teriamos esse crud para gerencial os uf's

**Comment by AlexandreVitorino** [comment]
https://github.com/orionteles/iesb-eleicoes/commit/2a321adb17e575a2766aa4bf9a96bf135e6a44aa

Uai CRUD serve pra isso, é necessário algo além mais do que um simples crud para gerenciar as ufs ?

**Comment by dougs007** [comment]
Não entendi sua dúvida @AlexandreVitorino.

**Comment by AlexandreVitorino** [comment]
Mano,"Digamos que amanhã teremos um UF novo, teriamos esse crud para gerencial os uf's"
?????

**Comment by dougs007** [comment]
Alguém poderia testar e caso haja exito, aceitar meu PR ?
